#这个会被直接执行
commands_to_optimize:
  - "echo 999999 | sudo tee /proc/sys/fs/nr_open"

#这些会被添加到 /etc/security/limits.conf
limits_conf_values:
  - "*   hard    nofile      999999"
  - "*   soft    nofile      999999"  

#这个会被添加到 /etc/sysctl.conf 并执行 sysctl -p  
sysctl_values:
  - name: fs.file-max
    value: 999999
  - name: net.ipv4.ip_conntrack_max 
    value:  999999
  - name: net.ipv4.netfilter.ip_conntrack_max 
    value:  999999
  #调整tcp的连接时间
  - name: net.ipv4.tcp_keepalive_time
    value: 60
  - name: net.ipv4.tcp_keepalive_probes
    value: 30
  - name: net.ipv4.tcp_keepalive_intvl
    value: 90
  #disable IPv6
  - name: net.ipv6.conf.default.disable_ipv6
    value: 1
  - name: net.ipv6.conf.all.disable_ipv6
    value: 1
  # General gigabit tuning
  - name: net.core.rmem_max 
    value:  16777216
  - name: net.core.wmem_max 
    value:  16777216
  # 这里设置的是tcp缓冲区, 分别为最小, 默认, 最大
  - name: net.ipv4.tcp_rmem 
    value:  4096 87380 16777216
  - name: net.ipv4.tcp_wmem 
    value:  4096 65536 16777216
  # This gives the kernel more memory for TCP
  # which you need with many (100k+) open socket connections
  - name: net.ipv4.tcp_mem 
    value:  50576 64768 98152
  # Backlog
  - name: net.core.netdev_max_backlog 
    value:  2048
  - name: net.core.somaxconn 
    value:  1024
  - name: net.ipv4.tcp_max_syn_backlog 
    value:  2048
  - name: net.ipv4.tcp_syncookies 
    value:  1
  - name: net.ipv4.tcp_tw_reuse 
    value:  1
  - name: net.ipv4.tcp_tw_recycle 
    value:  1
  - name: net.ipv4.tcp_fin_timeout 
    value:  30
  - name: net.ipv4.ip_local_port_range 
    value:  1024 65000    
