# file: roles/zookeeper/tasks/install.yml

- name: Zookeeper | Download the zookeeper source in /tmp if not yet present
  get_url: url={{zookeeper_download_url}} dest=/tmp/zookeeper-{{ zookeeper_version }}.tar.gz

- name: Zookeeper | Untar the zookeeper source in /usr/local/etc
  command: tar -xvzf /tmp/zookeeper-{{ zookeeper_version }}.tar.gz chdir=/opt creates=/opt/zookeeper-{{ zookeeper_version }}

- name: Zookeeper | Update the zookeeper install permissions
  file: path=/opt/zookeeper-{{ zookeeper_version }} owner={{ zookeeper_user }} group={{ zookeeper_group }} state=directory recurse=yes

- name: Zookeeper | Update the symbolic link to the zookeeper install
  file: path=/opt/zookeeper src=/opt/zookeeper-{{ zookeeper_version }} state=link force=yes

- name: Zookeeper | Make sure the local working directory for zookeeper is present
  file: path={{ zookeeper_data_dir }} owner={{ zookeeper_user }} group={{ zookeeper_group }} mode=0750 state=directory
  
# - name: Zookeeper | Inform the system where the zkCli.sh binary is located
#   alternatives: name="zkCli" path="/opt/zookeeper/bin/zkCli.sh"
#   
- name: Zookeeper | Inform the system where the zkCli.sh binary is located
  command: update-alternatives --install "/usr/bin/zkCli" "zkCli" "/opt/zookeeper/bin/zkCli.sh" 1

- name: Zookeeper | Inform the system that this zkCli.sh binary must be the default
  command: update-alternatives --set zkCli /opt/zookeeper/bin/zkCli.sh

