# file: roles/zookeeper/tasks/user.yml

- name: Zookeeper | Make sure the zookeeper group is present
  group: gid={{ zookeeper_gid }} name={{ zookeeper_group }} state=present


- name: Zookeeper | Make sure the zookeeper user is present
  user: uid={{ zookeeper_uid }} name={{ zookeeper_user }} group={{ zookeeper_group }}  shell=/sbin/nologin state=present comment="Zookeeper user"

