- include: user.yml

- name: Redis | Make sure redis data directory present
  file: path={{ redis_data_dir }} state=directory owner={{ redis_user }} group={{ redis_group }} mode=0750

- name: Redis | Download the redis source in /tmp if not yet present
  command: wget http://download.redis.io/redis-stable.tar.gz chdir=/tmp creates=/tmp/redis-stable.tar.gz

- name: Redis | Upload the redis install script
  template: src=redis-install.sh dest=/tmp/redis-install.sh owner=root group=root mode=0755

- name: Redis | Install redis using the install script
  shell: /tmp/redis-install.sh
  sudo: yes

- name: Redis | Install the supervisord redis script
  template: src=etc_supervisor.d_redis.conf.j2 dest=/etc/supervisor.d/redis.conf owner=root group=root mode=0644
  notify:
    - restart supervisor

- name: Redis | Configure the redis servers
  template: src=etc_redis.conf.j2 dest=/etc/redis.conf
  notify:
    - restart redis    


    