# file: roles/nginx/tasks/dependencies.yml

- name: Nginx | Make sure the nginx dependencies are installed
  yum: name={{ item }} state=present
  with_items:
    - git
    # - libgoogle-perftools-dev
    - pcre
    - pcre-devel
    - openssl
    - zlib
    - zlib-devel
