
# - name: Downloading and enable the EPEL repository definitions.
#   action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
#   # when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int == 6

- name: Downloading the EPEL repository definitions.
  get_url: dest=/tmp url=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm mode=0644

- name: Enable the EPEL repository
  action: command rpm -Uvh --replacepkgs /tmp/epel-release-6-8.noarch.rpm
  
  # when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int == 6