# the full qualified domain name, same as `hostname -v`
fqdn: localhost
hostname: localhost

common_packages:
  - libyaml
  - libyaml-devel
  - openssl
  - openssl-devel
  - zlib
  - zlib-devel
  - ImageMagick
  - lsof
  - htop
  - sysstat
  - iptraf-ng
  - wget
  - git
  - curl
  - htop
  - iftop
  - iotop
  - nmap
  - screen
#################################### EPEL #############################################
epel_download_url: http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
#################################### Tomcat ###########################################   
tomcat_download_url: http://mirror.bit.edu.cn/apache/tomcat/tomcat-7/v7.0.53/bin/apache-tomcat-7.0.53.tar.gz  

#################################### Build  ###########################################
#是否安装build相关的包, 默认为true
include_build_packages: true
build_packages:
  - autoconf
  - automake
  - binutils
  - bison
  - flex
  - gcc
  - gcc-c++
  - gettext
  - libtool
  - make
  - patch
  - pkgconfig
  - redhat-rpm-config
  - rpm-build
  