# file: roles/cron/tasks/main.yml

- name: Cron | Make sure cron is installed
  yum: pkg=crontabs state=present

- name: Cron | Make sure cron is enabled
  service: name=crond state=restarted enabled=yes
