# file: roles/cassandra/tasks/dependencies.yml

- name: Cassandra | Make sure the cassandra dependencies are installed
  yum: pkg={{ item }}
  with_items:
    - boost-devel
    - jna
    # - libboost-dev
    # - pkg-config
