# file: roles/cassandra/tasks/install.yml

- name: Cassandra | Download the cassandra source in /tmp if not yet present
  get_url: url={{ cassandra_download_url }} dest=/tmp/apache-cassandra-{{ cassandra_version }}-bin.tar.gz

- name: Cassandra | Expand the cassandra source in /usr/local/etc
  command: tar -xvzf /tmp/apache-cassandra-{{ cassandra_version }}-bin.tar.gz chdir=/opt creates=/opt/apache-cassandra-{{ cassandra_version }}

- name: Cassandra | Update the cassandra install permissions
  file: path=/opt/apache-cassandra-{{ cassandra_version }} owner={{ cassandra_user }} group={{ cassandra_group }} state=directory recurse=yes

- name: Cassandra | Update the symbolic link to the cassandra install
  file: path=/opt/cassandra src=/opt/apache-cassandra-{{ cassandra_version }} state=link force=yes

- name: Cassandra | Inform the system where the cassandra-cli binary is located
  command: update-alternatives --install "/usr/bin/cassandra-cli" "cassandra-cli" "/opt/cassandra/bin/cassandra-cli" 1

- name: Cassandra | Inform the system that this cassandra-cli binary must be the default
  command: update-alternatives --set cassandra-cli /opt/cassandra/bin/cassandra-cli

- name: Cassandra | Inform the system where the nodetool binary is located
  command: update-alternatives --install "/usr/bin/nodetool" "nodetool" "/opt/cassandra/bin/nodetool" 1

- name: Cassandra | Inform the system that this nodetool binary must be the default
  command: update-alternatives --set nodetool /opt/cassandra/bin/nodetool


- name: Cassandra | Make sure the local working (data) directory for cassandra is present
  file: path={{ cassandra_data_root_dir }} owner={{ cassandra_user }} group={{ cassandra_group }} mode=0750 state=directory

- name: Cassandra | Make sure the working subdirectories for cassandra are present
  file: path={{ cassandra_data_root_dir }}/{{ item }} owner={{ cassandra_user }} group={{ cassandra_group }} mode=0750 state=directory
  with_items:
    - data
    - commitlog
    - saved_caches
