# file: roles/cassandra/tasks/user.yml

- name: Cassandra | Make sure the cassandra group is present
  group: gid={{ cassandra_gid }} name={{ cassandra_group }} state=present

- name: Cassandra | Make sure the cassandra user is present
  user: uid={{ cassandra_uid }} name={{ cassandra_user }} group={{ cassandra_group }} shell=/sbin/nologin state=present comment="Cassandra user"