# file: roles/python/tasks/main.yml

- name: Python | Make sure python packages are installed
  yum: pkg={{ item }}
  with_items:
    - Cython
    - libevent
    - libevent-devel
    - python
    - python-devel
    - python-setuptools
    - python-pip

- name: Python | Make sure virtualenv is installed
  pip: name=virtualenv
