# file: roles/python/tasks/main.yml

- name: Python | Make sure python packages are installed
  yum: pkg={{ item }} state=present
  with_items: python_packages

- name: Python | Make sure python modules are installed
  pip: name={{ item }}
  with_items: python_modules
