# file: roles/kafka/meta/main.yml

dependencies:
  - { role: hostname }
  - { role: build }
  - { role: python }
  - { role: jdk }
  - { role: supervisor }
  - { role: tomcat }
  - { role: zookeeper }
  - { role: cassandra }
