# file: roles/tomcat/tasks/supervise_tomcat.yml

- name: Tomcat | Install the supervisord tomcat script
  template: src=etc_supervisor.d_tomcat.conf.j2 dest=/etc/supervisor.d/tomcat.conf owner=root group=root mode=0644
  notify:
    - restart supervisor
