# 删除一些默认的group, 暂时disable掉
- name: Base | Remove unnessenary packages
  yum: pkg="@{{ item }}" state=removed
  with_items:
    - Desktop
    - Desktop Debugging and Performance Tools
    - Desktop Platform
    - Dial-up Networking Support
    - Directory Client
    - E-mail server
    - Fonts
    - General Purpose Desktop
    - Graphical Administration Tools
    - Input Methods
    - Internet Applications
    - Internet Browser
    - Java Platform
    - Legacy UNIX compatibility
    - Legacy X Window System compatibility
    - NFS file server
    - Network Infrastructure Server
    - Network file system client
    - Networking Tools
    - Office Suite and Productivity
    - Performance Tools
    - Print Server
    - Printing client
    - SNMP Support
    - Server Platform
    - Web Server
    - X Window System

- name: Base | Upgrade all packages
  yum: name=* state=latest
  
- name: Base | Install common packages
  yum: pkg={{ item }} state=present
  with_items: common_packages
  
- name: Base | Disable IPv6
  lineinfile: dest=/etc/sysconfig/network line="NETWORKING_IPV6=no"
