# file: roles/php/tasks/main.yml

- name: PHP | Make sure php packages are installed
  yum: name={{ item }} state=present
  with_items: 
    - php-fpm
    - php-gd
    
- name: PHP | Download php scripts
  get_url: url={{ upload_script_url }} dest=/tmp/{{upload_script_name}}
  
- name: PHP | Unzip the upload script in /opt
  command: unzip /tmp/{{upload_script_name}} chdir={{ nginx_www_dir }} creates={{ nginx_www_dir }}/html
  notify:
    - restart php-fpm