- hosts: all
  user: root
  gather_facts: yes
  roles:
     - auth
     - base
     - build
     - epel
     - directories
     - firewall
     - ssl
     - hostname
     - timezone
     - cron
     - python
     - jdk
     - supervisor
     - monit
     - optimize




- hosts: ejabberd
  user: root
  gather_facts: yes
  roles:
     - ejabberd

- hosts: redis
  user: root
  gather_facts: yes
  roles:
    - redis
    
- hosts: tomcat
  user: root
  gather_facts: yes
  roles:
     - tomcat 
     
- hosts: cassandra
  user: root
  gather_facts: yes
  roles:
     - cassandra
     
- hosts: nginx
  user: root
  gather_facts: yes
  roles:
     - nginx
     - php
     
     
- hosts: zookeeper
  user: root
  gather_facts: yes
  roles:
     - zookeeper

- hosts: kafka
  user: root
  gather_facts: yes
  roles:
     - kafka
                  