- hosts: nginx
  user: root
  gather_facts: no
  vars_files: 
    - default_vars.yaml
    - users.yaml
    - cassandra.yaml
    - directories.yaml
    - jdk.yaml
    - supervisor.yaml
    - python.yaml
    - optimize.yaml
    - kafka.yaml
  vars:
    monit_protection: true
  roles:
     - auth
     - epel
     - directories
     - ssl
     - hostname
     - timezone
     - base
     - build
     - cron
     - python
     - jdk
     - supervisor
     - monit
     - nginx
     - cassandra
     - zookeeper
     - kafka
     - optimize
